### ISSUE TITLE
First use 1.15.2 Paper

### ISSUE THREAD

**Issue by ver151set** [Jikoo/Regionerator#21] opened 2020-05-17 15:42 UTC
[10:38:17] [Server thread/ERROR]: Error occurred while enabling Regionerator v2.0.1 (Is it up to date?)
java.lang.RuntimeException: An error occurred while setting up the database
	at com.github.jikoo.regionerator.ChunkFlagger.<init>(ChunkFlagger.java:53) ~[?:?]
	at com.github.jikoo.regionerator.Regionerator.onEnable(Regionerator.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-284]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-284]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Paper-284]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "ON": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:941) ~[patched_1.15.2.jar:git-Paper-284]
	at org.sqlite.core.DB.newSQLException(DB.java:953) ~[patched_1.15.2.jar:git-Paper-284]
	at org.sqlite.core.DB.throwex(DB.java:918) ~[patched_1.15.2.jar:git-Paper-284]
	at org.sqlite.core.NativeDB._exec_utf8(Native Method) ~[patched_1.15.2.jar:git-Paper-284]
	at org.sqlite.core.NativeDB._exec(NativeDB.java:94) ~[patched_1.15.2.jar:git-Paper-284]
	at org.sqlite.jdbc3.JDBC3Statement.executeUpdate(JDBC3Statement.java:109) ~[patched_1.15.2.jar:git-Paper-284]
	at com.github.jikoo.regionerator.ChunkFlagger.<init>(ChunkFlagger.java:43) ~[?:?]
	... 10 more

**Comment by ver151set** [comment] 2020-05-17 15:44
Ive tried deleting the data.db and letting it recreate it, same issue every time. Java 8 64 bit

**Comment by Jikoo** [comment] 2020-05-17 16:52
If you restart the server after that error and leave data.db intact, does Regionerator function?

**Comment by Jikoo** [comment] 2020-05-18 11:03
Cannot reproduce on paper 299.

Something in your setup appears to be causing the trigger creation statement to be called before the database is fully set up, which doesn't make sense because it's called after in the same method - there's no way that line should be hit without the database existing.

**Comment by ver151set** [comment] 2020-05-18 19:41
Yes, leaving database intact and restarting results in the exact same error. Config is default besides enabled world. I successfully used this plugin 1.9ish to 1.12.2 and recently upgraded to 1.15. Also tried with spigot 1.15.2

**Comment by Jikoo** [comment] 2020-05-19 10:41
How did you manage to get so ancient a SQLite version? The version packaged in CB/Spigot/Paper (org.xerial:sqlite-jdbc) is 3.30.1.

Either way, that's the problem, that version doesn't support the statement type used for the trigger. I don't really want to change this on my end. From a separate discussion of the SQLite requirements:

> I get that the plugin you want to use to provide the experience you're looking for on your server locks you into your software selection, but this is an additional side effect of making that choice. To replace the trigger would require me to at minimum double my interactions with the database and increase code complexity by quite a bit. I am not interested in adding a performance or quality hit like that, nor am I willing to devote my time to maintaining separate versions for outdated server software.

I guess I can just cause that feature to break for people running incredibly outdated software, but there's really no reason for you to be downgrading the version of SQLite bundled in Paper.

**Comment by ver151set** [comment] 2020-05-19 13:26
Ahhh. 

Im using Freenas with their plugin "Mineos" in a jail. Pkg repositories are linked to specific ones from them and that is what is available. Ill try using portsnap and getting a newer version.

Thanks

**Comment by Jikoo** [comment] 2020-05-19 15:28
[2.0.2](https://github.com/Jikoo/Regionerator/releases/tag/2.0.2) allows the plugin to enable with a failing trigger addition.

If the trigger addition fails, the plugin will log driver and db versions. Would still appreciate that info even though I'm closing this - if it's another issue I may need to investigate further.

**Comment by ver151set** [comment] 2020-05-20 00:36
Now it loads, but throws errors on updating chunk flags. Thank you for your time





[19:20:04] [Server thread/INFO]: [Regionerator] Enabling Regionerator v2.0.2
[19:20:04] [Server thread/INFO]: [Regionerator] Debug level: LOW
[19:20:04] [Server thread/WARN]: [Regionerator] Caught an exception setting up database trigger! Last visit before delete will not be available.
[19:20:04] [Server thread/WARN]: [Regionerator] SQLite driver: SQLite JDBC 3.30.1
[19:20:04] [Server thread/WARN]: [Regionerator] SQLite database: SQLite 3.15.1
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Civs hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Factions hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Feudal hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for GriefDefender hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for GriefPrevention hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Kingdoms hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Landlord hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Lands hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for PreciousStones hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for RedProtect hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Residence hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for Towny hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Enabled protection hook for WorldGuard
[19:20:04] [Server thread/INFO]: [Regionerator] Dependencies not found for UltimateClaims hook, skipping.
[19:20:04] [Server thread/INFO]: [Regionerator] Enabled protection hook for VanillaSpawnProtection






[19:30:23] [BatchExpiration/ERROR]: [Regionerator] Exception updating chunk flags
--
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "ON": syntax error)
at org.sqlite.core.DB.newSQLException(DB.java:941) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.core.DB.newSQLException(DB.java:953) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.core.DB.throwex(DB.java:918) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.core.DB.prepare(DB.java:257) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[patched_1.15.2.jar:git-Paper-300]
at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[patched_1.15.2.jar:git-Paper-300]
at com.github.jikoo.regionerator.ChunkFlagger.lambda$new$3(ChunkFlagger.java:102) ~[?:?]
at  com.github.jikoo.regionerator.util.BatchExpirationLoadingCache.lambda$checkExpiration$2(BatchExpirationLoadingCache.java:167)  ~[?:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by Jikoo** [comment] 2020-05-20 11:07
Neeeeat. I'll look into this more, but I can't make any promises - the included version of SQLite is actually the expected version, but it looks like the database just flat out isn't being made somehow.

**Comment by Jikoo** [comment] 2020-05-20 12:29
Oh. Your database is being created as an older version. 3.24.0 was when upserts were added, your database is 3.15.1. It wasn't the trigger that was the SQL issue, it was ON CONFLICT DO UPDATE.

Without a deep dive into the SQLite driver I have no idea why this would happen. As far as I can tell there are not any client settings available to control db version, but clearly your setup is resulting in unexpected behavior. Unfortunately, my searches have come up with nothing because all of the keywords usable have other meanings for databases.

**Comment by Jikoo** [comment] 2020-05-20 13:01
Sorry, won't be investing any more time in this. If anyone else has ideas or is willing to dive into it they're welcome to, but in my mind the best solution would be to ignore the cause of this oddity entirely and implement a system supporting older SQLite/other databases. Different database adapters comes further down on my list than NMS adapters, which is still a very long way out.

**Closed by Jikoo** 2020-05-20 13:01 UTC

**Comment by Jikoo** [comment] 2020-05-21 01:28
Thought about it more and realized that implementing support for older/different databases is actually super simple. Took the opportunity to improve and fix a couple minor issues, will hopefully have time to test the modern SQLite tomorrow and maybe push a release.

All calls on the older version are valid SQLite and should work, but I don't have a test environment for versions other than 1.15 any more.

**Comment by ver151set** [comment] 2020-05-28 00:20
Sweet, look forward to testing it out

**Comment by Jikoo** [comment] 2020-05-28 04:11
Sorry, meant to finish another request and tag a release but ended up getting sucked away. Here's a build of 2.0.3-SNAPSHOT, will ideally get back and push a release soon(TM).
[Regionerator.zip](https://github.com/Jikoo/Regionerator/files/4693169/Regionerator.zip) Rename to .jar, profit
